### ISSUE TITLE
Parsing sensor glucose values

### ISSUE THREAD

**Issue by twain47** [paulokow/decoding-contour-next-link#2]
I'm looking to extend this code to add sensor glucose history to the export and I'm wondering if you might  be able to help point me in the right direction given that the constants in the code include a few references to this?

**Comment by mortlind** [comment]
@twain47 I am looking at the same. When I look at history events, it seems that it would fit if those of type 'b' would be the rigth ones, since they arrive at 5 min. intervals. Hower, in `pump_history_parser.py` the event with type `0x0B` is the one with constant name `PLGM_CONTROLLER_STATE`, which I do not know what is. I would expect to see event of type `0xCC` with name `SENSOR_GLUCOSE_READINGS`. Has there been some change of protocol since the code was written? Is there some document with a specification of the payload format for the various types of events?

**Comment by twain47** [comment]
I see the same. Digging into the data in the 'b' events I see a couple of possible values that could be the sensor glucose:

```
 class PLGMControllerStateEvent(NGPHistoryEvent):
    def __init__(self, eventData):
        NGPHistoryEvent.__init__(self, eventData)

    def __str__(self):
        return '{0} {1} {2}'.format(NGPHistoryEvent.__str__(self), self.val1, self.val2)

    @property
    def val1(self):
        return struct.unpack('>H', self.eventData[13:15] )[0]

    @property
    def val2(self):
        return struct.unpack('>H', self.eventData[15:17] )[0]

````
I suspect val2 is the calculated sensor glucose and my guess is that val1 might be the raw ISIG value (but just a guess)

**Comment by mortlind** [comment]
I concur that 0x0B events seems to have correct SG value in eventData[15:17] in mg/dl.

**Comment by mortlind** [comment]
The following class picks out the sensor glucose:
```python
class SensorGlucoseReadingEvent(NGPHistoryEvent):
    def __init__(self, eventData):
        NGPHistoryEvent.__init__(self, eventData)
        
    def __str__(self):
        return '{0} {1}'.format(NGPHistoryEvent.__str__(self), self.sgValueM)

    @property
    def sgValue(self):
        # bgValue is always in mg/dL.
        return struct.unpack( '>H', self.eventData[15:17] )[0]

    @property
    def sgValueM(self):
        return self.sgValue / 18.016
```

Then it can be matched by the wrongly named event in the `NGPHistoryEvent.eventInstance` method on line 146 as follows:

```python
        elif self.eventType == NGPHistoryEvent.EVENT_TYPE.PLGM_CONTROLLER_STATE:
            return SensorGlucoseReadingEvent(self.eventData)
```

I would like to branch, rename the event types, and make a pull request, but it seems a bit unsafe as it is only based on qualified guesswork.

**Comment by paulokow** [comment]
Hi @twain47 , @mortlind  - thanks for supporting. I do not have CGM myself so cannot help, but the whole code was ported from https://github.com/tidepool-org/chrome-uploader/blob/pazaan/electron-medtronic600/lib/drivers/medtronic600/NGPHistoryParser.js and I think CGM parsing is there as well.

**Comment by mortlind** [comment]
@paulokow The tidepool repo also has this wrong with respect to my daughters pump. Could it be a model issue?

**Comment by paulokow** [comment]
@mortlind, as said I cannot confirm w/o CGM. For the record what pump you try with?
tidepool code is rather using SENSOR_GLUCOSE_READINGS_EXTENDED: 0xD6. Maybe this is the one?

@pazaan may also have a clue being an author of 640G module in tidepool repo

**Comment by pazaan** [comment]
@mortlind what model of pump do you have?

**Comment by pazaan** [comment]
SG Readings are `0xD6`

**Comment by mortlind** [comment]
@pazaan I have a 640g. I am pretty sure that I get SG readings from events of type 0x0B, as initially suggested by @twain47 . At least they are in correspondence with readings on the pump display. The 0xCC events, which should be SG according to the naming, are not arriving in the log, and neither are 0xD6 events. The 0x0B events are arriving regularly with 5 min intervals.

**Comment by pazaan** [comment]
0x0B are results for PLGM controller state. 0xCC are called SENSOR_GLUCOSE_READINGS, but are never used by CareLink. 0xD6 are SENSOR_GLUCOSE_READINGS_EXTENDED. These are the history results that CareLink Personal and CareLink Pro use to process historical SG readings.
You're welcome to try using 0x0B, but I'm just giving you feedback based on what I know already works.

**Comment by mortlind** [comment]
I understand, and I thank you for caring about it and doint a great effort! But I have a hard time getting SG from the log using 0xD6 events, since I have not seen any of those around, whereas I have plenty of 0x0B events. I suppose the cause may be newer firmware in my daughters pump, since it is only a couple of weeks old.

**Comment by pazaan** [comment]
0x0B is the state of the PLGM, which may well include SG. However, this wouldn't work for say, 620G or 630G which don't have predictive low glucose controllers.
To get the CGM data, you need to make a second request for [SENSOR historical data](https://github.com/tidepool-org/chrome-uploader/blob/pazaan/electron-medtronic600/lib/drivers/medtronic600/medtronic600Driver.js#L1461-L1466), which is different from the pump data.

See the [code I use to fetch history here](https://github.com/tidepool-org/chrome-uploader/blob/pazaan/electron-medtronic600/lib/drivers/medtronic600/medtronic600Driver.js#L1580-L1618).

**Comment by mortlind** [comment]
OK. I see that pump data history is implemented in the code here. I will have to look into that. Thanks for that information.

**Comment by mortlind** [comment]
@pazaan Are there any documents on the mechanism/structure/architectur for acquiring the pump and sensor data? Do I get the sensor data in the same way as you get pump data in the code?

**Comment by paulokow** [comment]
Hi @mortlind,
I added support to read also the sensor history in `getPumpHistory` and `getPumpHistoryInfo`. See `requestType` param. As said, without a pump with CGM I could not test.
Parsing of `SENSOR_GLUCOSE_READINGS_EXTENDED: 0xD6` is a bit complex so I'd rather not try to port it without any testing.

On the branch [paulokow/sensordata](https://github.com/paulokow/decoding-contour-next-link/tree/paulokow/sensordata) I enabled the CGM reading as well as dump of raw data to a file.
If you agree to post a dump from your reading `history_data.dat`, I would be able to test the parsing.

**Comment by mortlind** [comment]
Hi @paulokow, Very nice! I saw the commit, and will happily test it, and provide a history snippet. At the moment, and into next week, I am a bit busy with work matters. I will try to make it at the end of next week. If, however, you have a script for extracting and dumping the data as you wish it formatted, I can run it and upload right away.

**Comment by paulokow** [comment]
@mortlind, great, just run the `read_minimed_next24.py` from the branch `paulokow/sensordata`. It should save `history_data.dat` file I can then use.

**Comment by mortlind** [comment]
@paulokow Do you need that much history? Would it not suffice with one hour? I can do that change like the diff below. Another thing: In your code I do not see where you specify HISTORY_DATA_TYPE.SENSOR_DATA. It looks like it still only downloads pump data.

```diff
diff --git a/read_minimed_next24.py b/read_minimed_next24.py
index 3c3b7be..f25f90f 100755
--- a/read_minimed_next24.py
+++ b/read_minimed_next24.py
@@ -1318,14 +1318,20 @@ def pumpDownload(mt):
     print "Battery remaining: {0}%".format( status.batteryLevelPercentage )
     
     print "Getting history info"
-    historyInfo = mt.getPumpHistoryInfo(datetime.datetime(2017, 8, 23), datetime.datetime.max, HISTORY_DATA_TYPE.PUMP_DATA)
+    d_start = datetime.datetime.now()-datetime.timedelta(hours=1)
+    historyInfo = mt.getPumpHistoryInfo(d_start,
+                                        datetime.datetime.max,
+                                        HISTORY_DATA_TYPE.PUMP_DATA)
     #print binascii.hexlify( historyInfo.responsePayload,  )
     print " Start: {0}".format(historyInfo.datetimeStart)
     print " End: {0}".format(historyInfo.datetimeEnd);
     print " Size: {0}".format(historyInfo.historySize);
     
     print "Getting history"
-    history_pages = mt.getPumpHistory(historyInfo.historySize, datetime.datetime(2016, 1, 1), datetime.datetime.max, HISTORY_DATA_TYPE.PUMP_DATA)
+    history_pages = mt.getPumpHistory(historyInfo.historySize,
+                                      d_start,
+                                      datetime.datetime.max,
+                                      HISTORY_DATA_TYPE.PUMP_DATA)
 
     # uncomment to save events for testing without Pump (use: tests/process_saved_history.py)
     #with open('hisory_data.dat', 'wb') as output:
```

**Comment by mortlind** [comment]
@paulokow I do not get a `history_data.dat`, but I do get a `read_minimed.db`. Is that the data you need? I guess so, since `find . -name '*.py' | xargs grep history_data` gives me no hits.

**Comment by paulokow** [comment]
@mortlind , 1h of data shall be OK.
just change HISTORY_DATA_TYPE.PUMP_DATA to HISTORY_DATA_TYPE.SENSOR_DATA and uncomment the data dump.
```diff
diff --git a/read_minimed_next24.py b/read_minimed_next24.py
index 3c3b7be..8379414 100755
--- a/read_minimed_next24.py
+++ b/read_minimed_next24.py
@@ -20,7 +20,7 @@ import Crypto.Cipher.AES # pip install PyCrypto
 import sqlite3
 import hashlib
 import re
-#import pickle # needed for local history export
+import pickle # needed for local history export
 import lzo #pip install python-lzo
 from pump_history_parser import NGPHistoryEvent
 from pump_history_parser import BloodGlucoseReadingEvent
@@ -1318,18 +1318,18 @@ def pumpDownload(mt):
     print "Battery remaining: {0}%".format( status.batteryLevelPercentage )
     
     print "Getting history info"
-    historyInfo = mt.getPumpHistoryInfo(datetime.datetime(2017, 8, 23), datetime.datetime.max, HISTORY_DATA_TYPE.PUMP_DATA)
+    historyInfo = mt.getPumpHistoryInfo(datetime.datetime(2017, 8, 23), datetime.datetime.max, HISTORY_DATA_TYPE.SENSOR_DATA)
     #print binascii.hexlify( historyInfo.responsePayload,  )
     print " Start: {0}".format(historyInfo.datetimeStart)
     print " End: {0}".format(historyInfo.datetimeEnd);
     print " Size: {0}".format(historyInfo.historySize);
     
     print "Getting history"
-    history_pages = mt.getPumpHistory(historyInfo.historySize, datetime.datetime(2016, 1, 1), datetime.datetime.max, HISTORY_DATA_TYPE.PUMP_DATA)
+    history_pages = mt.getPumpHistory(historyInfo.historySize, datetime.datetime(2016, 1, 1), datetime.datetime.max, HISTORY_DATA_TYPE.SENSOR_DATA)
 
     # uncomment to save events for testing without Pump (use: tests/process_saved_history.py)
-    #with open('hisory_data.dat', 'wb') as output:
-    #    pickle.dump(history, output)
+    with open('history_data.dat', 'wb') as output:
+        pickle.dump(history_pages, output)
 
     events = mt.processPumpHistory(history_pages)
     print "# All events:"
```

**Comment by mortlind** [comment]
@paulokow I get the following exception. Are you able to fix it? I do get something in `history_data.dat` but I do not know if it is corrupt or wrong. Do you have an eaddress to send it to?
```
Traceback (most recent call last):
  File "./read_minimed_next24.py", line 1291, in downloadPumpSession
    downloadOperations(mt)
  File "./read_minimed_next24.py", line 1340, in pumpDownload
    events = mt.processPumpHistory(history_pages)
  File "./read_minimed_next24.py", line 1177, in processPumpHistory
    decodedBlocks = self.decodePumpSegment(segment)
  File "./read_minimed_next24.py", line 1127, in decodePumpSegment
    logger.error('History type in response: {0} {1}'.format(type(dataType), binascii.hexlify(dataType)))
TypeError: b2a_hex() argument 1 must be string or buffer, not int
```

**Comment by paulokow** [comment]
@mortlind, the exception is in the parser already, so it's OK (and proves the right history has been read). The dump file shall be OK. You may just attach to a comment.

**Comment by mortlind** [comment]
Example history:
[history_data.dat.gz](https://github.com/paulokow/decoding-contour-next-link/files/1326921/history_data.dat.gz)

**Comment by paulokow** [comment]
Functionality added with commit [0420219](https://github.com/paulokow/decoding-contour-next-link/commit/0420219deadbdb1908f2e65fbd484de2182e8091)
