### ISSUE TITLE
Bounds on fetching history data are not respected. 

### ISSUE THREAD

**Issue by mortlind** [paulokow/decoding-contour-next-link#3]
I try to get the history of events for the latest 30 minutes like this:
```
d0 = datetime.datetime.now()-datetime.timedelta(minutes=30)
historyInfo = mt.getPumpHistoryInfo(d0, datetime.datetime.max)
history_pages = mt.getPumpHistory(historyInfo.historySize, d0, datetime.datetime.max)
```
But this still gives me all history in the pump.

**Comment by paulokow** [comment]
@mortlind, are you sure it's giving you the whole history, not just more data than requested in the front?
The pump seems always to send the full pages with only guarantee that the requested period is included.

But I agree in general it could be fixed.

**Comment by mortlind** [comment]
@paulokow I think you are right. I see that the number of records it fetches varies greatly, though i use the same duration of the lates 1 hour of history. For sure this is a matter of fetching a whole multiplum of pages. This can probably not be fixed, in the sense that I wish to limit the amount of data transfer. But we could filter away the excess history in your interface code. That might be nice, understandable, and useful.
