### ISSUE TITLE
Double SG values at same timestamp 

### ISSUE THREAD

**Issue by mortlind** [paulokow/decoding-contour-next-link#5]
Once in a while, I get two SG values at exactly the same timestamp for some period of time; this may be from one sample to some 5-10 samples. The attached plot from my web application shows this behaviour. Any clue? I do admit that I have not thoroughly traced the origin of these extra data, but I will do that. I am asking to learn if the device actually may supply several SG values at the same timestamp, and if there is a way to distinguish the two simultaneous SG events; only one of them are shown in the plot on the pump display. Notice in the display of my web application that the SG from the status of the pump, shown at the top, is, naturally, unambiguous and corresponds to one of the values. It is the extracted SG event history that exhibits the double-value behaviour. 

![image](https://user-images.githubusercontent.com/5364433/31807955-4104b8ce-b571-11e7-93dc-233a084ba07a.png)

**Comment by paulokow** [comment]
Hi, as I still don't have CGM it's hard to comment on that.
If you'd post a dump of history last time I may take a look into that.
Strange enough it that the values are different and in the same time some are missing in the period before.

**Comment by mortlind** [comment]
@paulokow Now you mention it, I did previously think about if those double values came from some time in the past. I dropped that thought, because, as you see in the plot above, the double points seems to branch out from the point at -15 mins. This is the behaviour I observe every time this happens, so I dismissed that it could be random values from the past. However, in exactly the plot I attached in the previous comment, it is clear that the two double points forming the lower branch after -15 min. fit very nicely into the curve around -40 min. So if the points do come from the past, where some points were missing, it is mysterious that they are pasted into the newer history where they seem to "fit". I will try to make a history dump and send it to you, the next time this occurs.

**Comment by mortlind** [comment]
@paulokow Now that I have looked at more of these branches it seems that a number of points corresponding to the number of points in the fake branch are always missing. And if the fake branch is reflected in time through the branching point, then it exactly makes up the missing points. So, I think this has to do with some arithmetics in deriving the `SensorGlucoseReadingEvent`s from within the `SensorGlucoseReadingsEvent`. I will try to look into this.

**Comment by cfaagaard** [comment]
Look at this: https://github.com/tidepool-org/chrome-uploader/blob/e747b329812d5fa9cb3e5ea88a547bebfb2a2152/lib/drivers/medtronic600/NGPHistoryParser.js#L291
The SensorGlucoseReadingsEvent can contain multiple readings and then you need to add "minutesBetweenReadings" to the timestamp.

**Comment by mortlind** [comment]
@paulokow My best theory about the reason for these branches is the pump losing contact with the sensor transmitter for a short time. The transmitter stores the SG-values, and once contact with the pump is established, the pump can read out the saved SG values. These values supposedly have an offset time with respect to some other point. In the current code this offset time is added to the time of the reference point, whereas they should have been subtracted.

This is becoming an increasing problem, since we observe that the frequency of the pump losing signal from the transmitter is increasing. It can get quite difficult to grasp the history sometimes.

![20171126111236](https://user-images.githubusercontent.com/5364433/33239174-9b5e017a-d29c-11e7-9933-08c9cee95f7b.jpg)

**Comment by paulokow** [comment]
Fixed in  f07459f
