### ISSUE TITLE
Switch to Python3

### ISSUE THREAD

**Issue by mortlind** [paulokow/decoding-contour-next-link#6]
I tried doing a simple 2to3.py on the code base once. There is a lot of string to byte conversion in the IO left to be done after the simple 2to3 conversion. This seems to now having been done in the @pazaan repo. Is it possible to merge this over to the @paulokow repo?

**Comment by pazaan** [comment]
I'm working on merging this repo into mine right now ;)

**Comment by mortlind** [comment]
@pazaan Really nice. I have been wondering for a while, why the good work of @paulokow was not merged into your branch :-)

**Comment by pazaan** [comment]
The only reason is that I’ve been away from home for 2 months, without access to devices for testing (my daughter is the PwD).

**Comment by mortlind** [comment]
@pazaan That is very understandable!

**Comment by mortlind** [comment]
@pazaan I just tested running you repo version under Python3 and it seems there is a lot left to do with converting to bytes and bytearray in all the IO data. Is it me who are mistaken? I never tried the  commit of @InsulinJunkieDE in which the commit message was saying "Make it work in Python3". Inspecting that commit, it looks a bit like a simple 2to3, which does not address the byte and string conversion.

**Comment by pazaan** [comment]
@mortlind I just merged the PR and tested that it didn't break anything, so you're probably correct. Can you open a Python 3 support ticket in my repo?
